"""rename department

Revision ID: 55fa4b5e5e62
Revises: d4220f00af4d
Create Date: 2024-06-27 23:31:42.349725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fa4b5e5e62'
down_revision = 'd4220f00af4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
